---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## Bridging the gap among community phylogenetics, biogeography and macroevolution
### Outline

Detect patterns of biodiversity distribution essential in Community ecology and Biogeography studies, since patterns allows test hypotheses and search for the processes generating those patterns. However, this pattern-oriented approach have not shown adequate to understand the underlying processes in a given assemblage, since similar patterns can be generated by totally different evolutionary processes, and the contrary, very different patterns could be generated by the same ecological/macroevolutionary process.

In this presentation I will show how we can improve our capacity to detect unanbiguous patterns and processes generating the distribution of biological diversity, with a special focus on the analysis of two very popular metrics used in biogeography and conservation studies: [Phylogenetic Diversity](https://www.sciencedirect.com/science/article/pii/0006320792912013)  and [Phylogenetic Endemism](https://onlinelibrary.wiley.com/doi/10.1111/j.1365-294X.2009.04311.x). 

I will demonstrate that by ignoring deep-time events that occurred in the evolutionary history of lineages lead to wrong conclusions about the processes affecting the assembly of communities and biogeographical regions. Further, I will propose a methodological solution to this problem that will pave the way to the development of a new family of metrics of phylogenetic diversity able to differentiate the effects of two main processes responsible to shape the distribution of life on earth: historical dispersal and diversification.


